name: Bug Report
description: Create a bug report to help us keep track of all bugs that have to be fixed
title: "[BUG] <name for bug>"
labels: [bug]

body:
  - type: checkboxes
    id: i-have-checked
    attributes:
      label: I have checked...
      options:
        - label: "I am using the latest version of BackpackPlus"
          required: true
        - label: "I have checked if any similar bug reports exist"
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A full description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Explain how to reproduce this issue step-by-step, in as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: system-report
    attributes:
      label: System Report
      description: |
        Please fill out the information manually in the following format:

        ### System Report
        **Plugin Version:**
        - BackpackPlus: <version>

        **Server Information:**
        - Software: <paper/spigot/etc>
        - Version: <full version (e.g. 1.20.1)>

        **System Information:**
        - OS: <operating system>
        - Java Version: <e.g. Java 17/21>
    validations:
      required: true
  - type: "dropdown"
    id: "type"
    attributes:
      label: "How breaking is the bug?"
      options:
        - "Breaking Bug - Plugin unusable"
        - "Non-breaking Bug - Plugin still usable, but certain features unavailable"
        - "Minor Bug - Plugin completely functional, but features have non-working aspects"
    validations:
      required: true
